<a href="https://colab.research.google.com/github/NikhilKumarReddyKadiveti/MLA0204/blob/main/Practical%20Problem%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import os

def find_s_algorithm(training_data):
    """
    Implements the FIND-S algorithm to find the most specific hypothesis.

    Args:
        training_data (list of lists): A list of training examples, where each
                                      example is a list of attribute values
                                      followed by the classification (e.g., 'yes' or 'no').

    Returns:
        list: The most specific hypothesis.
    """
    # Initialize the most specific hypothesis with the most specific possible values ('0')
    num_attributes = len(training_data[0]) - 1
    hypothesis = ['0'] * num_attributes

    print("\nInitialization of Hypothesis:", hypothesis)

    for i, example in enumerate(training_data):
        attributes = example[:-1] # All but the last element are attributes
        target = str(example[-1]).strip().lower() # Normalize case for matching

        if target == 'yes':
            print(f"\nProcessing Positive Example {i+1}: {example}")
            # If it's the first positive example, initialize hypothesis directly
            if hypothesis[0] == '0':
                hypothesis = list(attributes)
                print("   Hypothesis updated to first positive example:", hypothesis)
            else:
                # Generalize hypothesis for each attribute
                for j in range(num_attributes):
                    if str(hypothesis[j]).lower() != str(attributes[j]).lower():
                        hypothesis[j] = '?' # Generalize if attributes differ
                print("   Hypothesis after generalization:", hypothesis)
        else:
            print(f"\nIgnoring Negative Example {i+1}: {example}")

    return hypothesis

# --- Load data from file ---
file_path = '/content/enjoysport.csv'

if os.path.exists(file_path):
    # Read the dataset using pandas
    df = pd.read_csv(file_path)
    print("Training Data (DataFrame) Loaded from File:")
    display(df)

    # Convert DataFrame to a list of lists format
    training_data = df.values.tolist()

    # Run the FIND-S algorithm
    most_specific_hypothesis = find_s_algorithm(training_data)

    print("\n--- Result ---")
    print("The most specific hypothesis is:", most_specific_hypothesis)
else:
    print(f"Error: The file '{file_path}' was not found. Please make sure the file is uploaded or available in the path.")

Training Data (DataFrame) Loaded from File:

     sky airtemp humidity    wind water forcast enjoysport
0  sunny    warm   normal  strong  warm    same        yes
1  sunny    warm     high  strong  warm    same        yes
2  rainy    cold     high  strong  warm  change         no
3  sunny    warm     high  strong  cool  change        yes

Initialization of Hypothesis: ['0', '0', '0', '0', '0', '0']

Processing Positive Example 1: ['sunny', 'warm', 'normal', 'strong', 'warm', 'same', 'yes']
   Hypothesis updated to first positive example: ['sunny', 'warm', 'normal', 'strong', 'warm', 'same']

Processing Positive Example 2: ['sunny', 'warm', 'high', 'strong', 'warm', 'same', 'yes']
   Hypothesis after generalization: ['sunny', 'warm', '?', 'strong', 'warm', 'same']

Ignoring Negative Example 3: ['rainy', 'cold', 'high', 'strong', 'warm', 'change', 'no']

Processing Positive Example 4: ['sunny', 'warm', 'high', 'strong', 'cool', 'change', 'yes']
   Hypothesis after generalization: ['sunny', 'warm', '?', 'strong', '?', '?']

--- Result ---
The most specific hypothesis is: ['sunny', 'warm', '?', 'strong', '?', '?']

### Applying FIND-S with `enjoysport.csv`

Let's load the provided `enjoysport.csv` file and use it as our training data for the FIND-S algorithm.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# Load the enjoysport.csv file
df_enjoysport = pd.read_csv('/content/enjoysport.csv')

print("Data from enjoysport.csv:")
display(df_enjoysport.head())

# Convert DataFrame to the list of lists format expected by find_s_algorithm
# Assuming the last column is the target ('EnjoySport')
training_data_csv = df_enjoysport.values.tolist()

print("\nTraining data (list format) from enjoysport.csv:")
for row in training_data_csv:
    print(row)

# Run the FIND-S algorithm with the data from the CSV
most_specific_hypothesis_csv = find_s_algorithm(training_data_csv)

print("\n--- Result for enjoysport.csv ---")
print("The most specific hypothesis based on enjoysport.csv is:", most_specific_hypothesis_csv)

Data from enjoysport.csv:

     sky airtemp humidity    wind water forcast enjoysport
0  sunny    warm   normal  strong  warm    same        yes
1  sunny    warm     high  strong  warm    same        yes
2  rainy    cold     high  strong  warm  change         no
3  sunny    warm     high  strong  cool  change        yes

Training data (list format) from enjoysport.csv:
['sunny', 'warm', 'normal', 'strong', 'warm', 'same', 'yes']
['sunny', 'warm', 'high', 'strong', 'warm', 'same', 'yes']
['rainy', 'cold', 'high', 'strong', 'warm', 'change', 'no']
['sunny', 'warm', 'high', 'strong', 'cool', 'change', 'yes']

Initialization of Hypothesis: ['0', '0', '0', '0', '0', '0']

Processing Positive Example 1: ['sunny', 'warm', 'normal', 'strong', 'warm', 'same', 'yes']
   Hypothesis updated to first positive example: ['sunny', 'warm', 'normal', 'strong', 'warm', 'same']

Processing Positive Example 2: ['sunny', 'warm', 'high', 'strong', 'warm', 'same', 'yes']
   Hypothesis after generalization: ['sunny', 'warm', '?', 'strong', 'warm', 'same']

Ignoring Negative Example 3: ['rainy', 'cold', 'high', 'strong', 'warm', 'change', 'no']

Processing Positive Example 4: ['sunny', 'warm', 'high', 'strong', 'cool', 'change', 'yes']
   Hypothesis after generalization: ['sunny', 'warm', '?', 'strong', '?', '?']

--- Result for enjoysport.csv ---
The most specific hypothesis based on enjoysport.csv is: ['sunny', 'warm', '?', 'strong', '?', '?']